In [1]:
import numpy as np

In [2]:
x=[[1,2,3],[2,3,4],[5,6,7]]

In [3]:
a=np.array(x)

In [4]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [5]:
a.shape

(3, 3)

In [6]:
a.size

9

In [7]:
a.sum(axis=0)

array([ 8, 11, 14])

In [8]:
a.sum(axis=1)

array([ 6,  9, 18])

In [9]:
a.T #it transpose the matrix

array([[1, 2, 5],
       [2, 3, 6],
       [3, 4, 7]])

In [10]:
a.flat #iterator

In [11]:
for item in a.flat:
    print(item)

1
2
3
2
3
4
5
6
7


In [12]:
a.ndim #it gave it beacause dimensions are 2

2

In [13]:
a.size

9

In [14]:
a.nbytes #total bytes consumed

72

In [15]:
one=np.array([1,3,4,644,2])

In [16]:
one.argmax() #it provides  index of max elemeny

np.int64(3)

In [17]:
one.argmin() #index of min element

np.int64(0)

In [18]:
one.argsort() # it sorts the element but it give the order of indexed

array([0, 4, 1, 2, 3])

In [19]:
 a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [20]:
a.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [21]:
a.argmin()

np.int64(0)

In [22]:
a.argmax()

np.int64(8)

In [23]:
a.argmax(axis=0)

array([2, 2, 2])

In [24]:
a.argmax(axis=1)

array([2, 2, 2])

In [25]:
a.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [26]:
a.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [27]:
a.ravel()

array([1, 2, 3, 2, 3, 4, 5, 6, 7])

In [28]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

***matrix operation***

In [29]:
ae=np.array(a)

In [30]:
ae

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [31]:
ar2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [32]:
arr2

NameError: name 'arr2' is not defined