In [1]:
import numpy as np

In [2]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [3]:
ar=np.array(a)

In [4]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b=[[12,23,13],[34,45,56],[56,67,78]]

In [6]:
ar1=np.array(b)

In [7]:
ar1

array([[12, 23, 13],
       [34, 45, 56],
       [56, 67, 78]])

In [8]:
ar+ar1

array([[13, 25, 16],
       [38, 50, 62],
       [63, 75, 87]])

In [9]:
[1,2,3]+[3,4,5]

[1, 2, 3, 3, 4, 5]

In [10]:
ar*ar1

array([[ 12,  46,  39],
       [136, 225, 336],
       [392, 536, 702]])

In [11]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [12]:
ar.sum()

np.int64(45)

In [13]:
ar.max()

np.int64(9)

In [14]:
ar.min()

np.int64(1)

In [15]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
type(np.where(ar>5))

tuple

In [18]:
np.count_nonzero(ar)

9

In [19]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [21]:
ar[1,2]=0

In [22]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [23]:
import sys

In [24]:
ch_ar=[0,4,55,2]

In [25]:
ch_ar

[0, 4, 55, 2]

In [26]:
np_ar=np.array(ch_ar)

In [27]:
np_ar

array([ 0,  4, 55,  2])

In [29]:
sys.getsizeof(1)*len(ch_ar) #it says abt it gives sizeof one element *into number of elements

112

In [30]:
np_ar.itemsize *np_ar.size


32

In [31]:
np_ar.tolist()

[0, 4, 55, 2]